# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Go Clean"
license = "MIT"
licenselink = "https://github.com/rig0rmortis/go-clean/blob/master/LICENSE.md"
description = "A clean and simple theme for Hugo"
homepage = "https://github.com/rig0rmortis/go-clean"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "rig0rmortis"
  homepage = "https://rig0rmortis.com"
